version: '3.3'
services:
  socialmarket:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - socialmarketnet
    # ports:
    #   - 9980:8080
    #   - 35729:35729
    #   - 5005:5005
networks:
  socialmarketnet:    