export const USERSDBPATH='user_dbpath'
export const TOKENNAME='user_social-market-token'
export const USERSERVICE='user_service'
export const USERLOGPATH='user_log'
export const USEREMAIL='user_email'
export const USERNAME='user_name'