export const USERSDBPATH='user:dbpath'
export const TOKENNAME='user:social-market-token'
export const USERSERVICE='user:service'
export const USERLOGPATH='user:log'
export const USEREMAIL='user:email'