CREATE TABLE IF NOT EXISTS email_template(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title VARCHAR(255),
content TEXT,
description VARCHAR(500) NULL,
status INTEGER DEFAULT 1,
buckemailTaskId INTEGER,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (buckemailTaskId) REFERENCES buckemail_task(id)
) 