CREATE TABLE IF NOT EXISTS email_filter_task_relation(
id INTEGER PRIMARY KEY AUTOINCREMENT,
emailFilterId INTEGER NOT NULL,
buckemailTaskId INTEGER NOT NULL,
status INTEGER DEFAULT 1,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (emailFilterId) REFERENCES email_filter(id) ON DELETE CASCADE,
FOREIGN KEY (buckemailTaskId) REFERENCES buckemail_task(id) ON DELETE CASCADE,
UNIQUE(emailFilterId, buckemailTaskId)
) 