CREATE TABLE IF NOT EXISTS email_service(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(255),
from_email VARCHAR(255),
password VARCHAR(255),
host VARCHAR(255),
port VARCHAR(10),
ssl INTEGER DEFAULT 1,
status INTEGER DEFAULT 1,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
) 