CREATE TABLE IF NOT EXISTS email_service_task_relation(
id INTEGER PRIMARY KEY AUTOINCREMENT,
emailServiceId INTEGER,
buckemailTaskId INTEGER,
status INTEGER DEFAULT 1,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (emailServiceId) REFERENCES email_service(id) ON DELETE CASCADE,
FOREIGN KEY (buckemailTaskId) REFERENCES buckemail_task(id) ON DELETE CASCADE
) 