CREATE TABLE IF NOT EXISTS proxy(
id INTEGER PRIMARY KEY AUTOINCREMENT,
host TEXT NOT NULL,
port TEXT NOT NULL,
user TEXT NULL,
pass TEXT NULL,
protocol TEXT NULL,
country_code TEXT NULL,
addtime TEXT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) 