import { contextBridge, ipcRenderer } from 'electron'
import {EXTRAMODULECHANNE_LIST,EXTRAMODULECHANNE_INSTALL,EXTRAMODULECHANNE_UNINSTALL,EXTRAMODULECHANNE_MESSAGE,OPENDIRECTORY,SYSTEM_MESSAGE,VIDEODOWNLOAD_MESSAGE,VIDEODOWNLOAD,VIDEODOWNLOAD_TASK_LIST,SEARCHSCRAPERAPI,LISTSESARCHRESUT,SEARCHEVENT,TASKSEARCHRESULTLIST,SAVESEARCHERRORLOG
  ,CHECKALLPROXY,CHECKALLPROXYMESSAGE,REMOVEFAILUREPROXY_MESSAGE,REMOVEFAILUREPROXY,EMAILEXTRACTIONAPI,EMAILEXTRACTIONMESSAGE,
  LISTEMAILSEARCHTASK,EMAILSEARCHTASKRESULT,EMAILMARKETINGTEMPLIST,EMAILMARKETINGTEMPREMOVE,EMAILMARKETINGTEMPDETAIL,EMAILMARKETINGTEMPUPDATE,EMAILMARKETINGFILTERLIST,EMAILMARKETFILTERDETAIL,EMAILMARKETFILTERUPDATE,EMAILSERVICEUPDATE,EMAILSERVICEDETAIL,EMAILSERVICELIST,EMAILSERVICEDELETE
  ,EMAILFILTERDELETE,BUCKEMAILSEND,BUCKEMAILSENDMESSAGE,SENDTESTEMAIL,RECEIVESENDTESTEMAILMESSAGE,BUCKEMAILTASKLIST,BUCKEMAILTASKSENDLOG,SOCIALACCOUNTlIST,SOCIALACCOUNTSAVE,SOCIAL_ACCOUNT_LOGIN_MESSSAGE,SOCIAL_ACCOUNT_LOGIN_UPLOADCOOKIES,SOCIAL_ACCOUNT_CLEAN_COOKIES,SOCIAL_ACCOUNT_SHOW_PLATFORMPAGE,
  VIDEODOWNLOAD_LIST,VIDEODOWNLOADTASK_RETRY,VIDEODOWNLOADITEM_RETRY,VIDEODOWNLOAD_ITEM_MESSAGE,VIDEODOWNLOADITEM_EXPLORER,VIDEODOWNLOADITEM_DELETE,VIDEODOWN_TASK_ERROR_LOG_QUERY,VIDEO_CAPTION_GENERATE,VIDEO_CAPTION_GENERATE_MESSAGE,EXTRAMODULE_UPGRADE,EXTRAMODULE_UPGRAD_MESSAGE,VIDEOTASKDOWNLOAD_RETRY_MESSAGE,VIDEODOWNLOAD_LOG_QUERY,VIDEODOWNLOAD_DETAIL_QUERY,VIDEODOWNLOAD_OPEN_CAPTIONFILE,
  SYSTEM_SETTING_LIST,SYSTEM_SETTING_UPDATE,VIDEO_INFORMATION_TRANSLATE,QUERY_USER_INFO,OPENLOGINPAGE,NATIVATECOMMAND,VIDEO_PUBLISH,EMAILSEARCHTASK_ERROR_LOG_DOWNLOAD,RETRYSEARCHTASK,CHOOSEFILEDIALOG,VIDEO_PUBLISH_RECORD_LIST,VIDEO_PUBLISH_RECORD_DELETE,VIDEO_PUBLISH_RECORD_MESSAGE,PROXYLIST,PROXYDETAIL,PROXYSAVE,PROXYCHECK,PROXYIMPORT,PROXYDELETE,
  // Schedule Management Channels
  SCHEDULE_CREATE,SCHEDULE_UPDATE,SCHEDULE_DELETE,SCHEDULE_ENABLE,SCHEDULE_DISABLE,SCHEDULE_PAUSE,SCHEDULE_RESUME,SCHEDULE_RUN_NOW,SCHEDULE_LIST,SCHEDULE_DETAIL,SCHEDULE_BY_TASK_TYPE,SCHEDULE_SEARCH,SCHEDULE_EXPORT,SCHEDULE_IMPORT,
  // Execution Management Channels
  EXECUTION_HISTORY,EXECUTION_STATISTICS,EXECUTION_RECENT,
  // Dependency Management Channels
  DEPENDENCY_ADD,DEPENDENCY_REMOVE,DEPENDENCY_GRAPH,DEPENDENCY_VALIDATE,
  // Scheduler Management Channels
  SCHEDULER_STATUS,SCHEDULER_START,SCHEDULER_STOP,SCHEDULER_RELOAD,
  // Utility Channels
  CRON_VALIDATE,GET_LOGIN_URL} from "@/config/channellist";

// window.ipcRenderer = ipcRenderer
// console.log('preload.js')
// contextBridge.exposeInMainWorld('electronAPI', {
//     userLogin: (data) => ipcRenderer.invoke('user:login', data)
// })
contextBridge.exposeInMainWorld('api', {
    send: (channel, data) => {
      // whitelist channels
      const validChannels = ['user:Login','socialtask:start','socialtask:log','socialaccount:login',EXTRAMODULECHANNE_INSTALL,EXTRAMODULECHANNE_MESSAGE,EXTRAMODULECHANNE_UNINSTALL,VIDEODOWNLOAD_MESSAGE,
        VIDEODOWNLOAD,SEARCHSCRAPERAPI,CHECKALLPROXY,REMOVEFAILUREPROXY,EMAILEXTRACTIONAPI,BUCKEMAILSEND,BUCKEMAILSENDMESSAGE,SENDTESTEMAIL,SOCIAL_ACCOUNT_LOGIN_UPLOADCOOKIES,SOCIAL_ACCOUNT_CLEAN_COOKIES,SOCIAL_ACCOUNT_SHOW_PLATFORMPAGE,VIDEODOWNLOADTASK_RETRY,VIDEODOWNLOADITEM_RETRY,VIDEODOWNLOADITEM_EXPLORER,VIDEODOWNLOADITEM_DELETE,VIDEO_CAPTION_GENERATE,EXTRAMODULE_UPGRADE,VIDEODOWNLOAD_OPEN_CAPTIONFILE,VIDEO_INFORMATION_TRANSLATE,OPENLOGINPAGE,VIDEO_PUBLISH,RETRYSEARCHTASK,VIDEO_PUBLISH_RECORD_DELETE]
      console.log('send',channel,data)
      if (validChannels.includes(channel)) {
        console.log('send2',channel,data)
        ipcRenderer.send(channel, data)
      }
    },
    receive: (channel, func) => {
      const validChannels = ['user:Login','socialtask:start','socialtask:log',EXTRAMODULECHANNE_INSTALL,EXTRAMODULECHANNE_MESSAGE,EXTRAMODULECHANNE_UNINSTALL,SYSTEM_MESSAGE,VIDEODOWNLOAD_MESSAGE,VIDEODOWNLOAD,
        SEARCHSCRAPERAPI,SEARCHEVENT,CHECKALLPROXYMESSAGE,REMOVEFAILUREPROXY_MESSAGE,EMAILEXTRACTIONMESSAGE,BUCKEMAILSENDMESSAGE,RECEIVESENDTESTEMAILMESSAGE,SOCIAL_ACCOUNT_LOGIN_MESSSAGE,SOCIAL_ACCOUNT_CLEAN_COOKIES,VIDEODOWNLOAD_ITEM_MESSAGE,VIDEO_CAPTION_GENERATE_MESSAGE,EXTRAMODULE_UPGRAD_MESSAGE,VIDEOTASKDOWNLOAD_RETRY_MESSAGE,VIDEO_INFORMATION_TRANSLATE,NATIVATECOMMAND,VIDEO_PUBLISH_RECORD_MESSAGE]
      const regex="/^socialtask:log:/"

      if (validChannels.includes(channel)||channel.test(regex)) {
        // Deliberately strip event as it includes `sender`
        ipcRenderer.on(channel, (event, ...args) => func(...args))
      }
    },
    invoke: (channel, data) => {
      // whitelist channels
      const validChannels = ['user:Login','user:checklogin','user:Signout','campaign:list','socialtask:list','socialtask:info','socialtasktype:list','tag:list','socialtask:save','socialtask:start','socialtaskrun:list','socialtaskresult:list',SOCIALACCOUNTlIST,SOCIALACCOUNTSAVE,'socialplatform:list','socialaccount:detail','socialaccount:delete',PROXYLIST,PROXYDELETE,PROXYSAVE,PROXYDETAIL,PROXYCHECK,PROXYIMPORT,EXTRAMODULECHANNE_LIST,OPENDIRECTORY,VIDEODOWNLOAD,VIDEODOWNLOAD_TASK_LIST,LISTSESARCHRESUT,SEARCHSCRAPERAPI,TASKSEARCHRESULTLIST,
        SAVESEARCHERRORLOG,LISTEMAILSEARCHTASK,EMAILSEARCHTASKRESULT,EMAILMARKETINGTEMPLIST,EMAILMARKETINGTEMPREMOVE,EMAILMARKETINGTEMPDETAIL,
        EMAILMARKETINGTEMPUPDATE,EMAILMARKETINGFILTERLIST,EMAILMARKETFILTERDETAIL,EMAILMARKETFILTERUPDATE,EMAILSERVICEUPDATE,EMAILSERVICEDETAIL,EMAILSERVICELIST,EMAILSERVICEDELETE,EMAILFILTERDELETE,BUCKEMAILTASKLIST,BUCKEMAILTASKSENDLOG,VIDEODOWNLOAD_LIST,VIDEODOWN_TASK_ERROR_LOG_QUERY,VIDEODOWNLOAD_LOG_QUERY,VIDEODOWNLOAD_DETAIL_QUERY,SYSTEM_SETTING_LIST,SYSTEM_SETTING_UPDATE,QUERY_USER_INFO,EMAILSEARCHTASK_ERROR_LOG_DOWNLOAD,RETRYSEARCHTASK,CHOOSEFILEDIALOG,VIDEO_PUBLISH_RECORD_LIST,
        // Schedule Management Channels
        SCHEDULE_CREATE,SCHEDULE_UPDATE,SCHEDULE_DELETE,SCHEDULE_ENABLE,SCHEDULE_DISABLE,SCHEDULE_PAUSE,SCHEDULE_RESUME,SCHEDULE_RUN_NOW,SCHEDULE_LIST,SCHEDULE_DETAIL,SCHEDULE_BY_TASK_TYPE,SCHEDULE_SEARCH,SCHEDULE_EXPORT,SCHEDULE_IMPORT,
        // Execution Management Channels
        EXECUTION_HISTORY,EXECUTION_STATISTICS,EXECUTION_RECENT,
        // Dependency Management Channels
        DEPENDENCY_ADD,DEPENDENCY_REMOVE,DEPENDENCY_GRAPH,DEPENDENCY_VALIDATE,
        // Scheduler Management Channels
        SCHEDULER_STATUS,SCHEDULER_START,SCHEDULER_STOP,SCHEDULER_RELOAD,
        // Utility Channels
        CRON_VALIDATE,GET_LOGIN_URL]
      if (validChannels.includes(channel)) {
        return ipcRenderer.invoke(channel, data)
      }
    }
  })